# Generated by Django 4.0.6 on 2022-09-28 12:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_delete_contact'),
        ('contact', '0002_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='course_choice',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
