# Generated by Django 4.0.6 on 2022-08-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
